spring:
  application:
    name: provider-service
dubbo:
  application:
    name: provider-zookeeper-service
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.martain.provide.service
  metadata-report:
    address: zookeeper://127.0.0.1:2181